# Generated by Django 2.2 on 2019-08-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tmp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('gid', models.CharField(max_length=20)),
                ('num', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
