# Generated by Django 2.2 on 2019-08-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tmp', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='ishot',
            field=models.IntegerField(default=1),
        ),
    ]
