# Generated by Django 2.2 on 2019-08-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tmp', '0005_auto_20190824_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_category',
            name='parentid',
            field=models.IntegerField(verbose_name='父id'),
        ),
    ]
