# Generated by Django 2.0 on 2019-08-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60)),
                ('parentid', models.IntegerField()),
            ],
            options={
                'db_table': 'goods_category',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('isactivation', models.IntegerField()),
                ('usertype', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=13)),
                ('birthday', models.CharField(max_length=50)),
                ('native_place', models.CharField(max_length=13)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('signature', models.CharField(max_length=100)),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='lingshi_admin.User')),
            ],
        ),
    ]
