# Generated by Django 2.0 on 2019-08-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lingshi_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_info',
            table='user_info',
        ),
    ]
