# Generated by Django 2.0 on 2019-08-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingshi_admin', '0002_auto_20190822_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
