# Generated by Django 2.0 on 2019-08-22 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lingshi_admin', '0003_user_info_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='uid',
            field=models.OneToOneField(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='lingshi_admin.User'),
        ),
    ]
