# Generated by Django 2.0 on 2019-08-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingshi_admin', '0004_auto_20190822_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isdel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
