# Generated by Django 2.0 on 2019-08-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingshi_admin', '0006_user_info_chathead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='chathead',
            field=models.CharField(default='/static/admin/upload/default.gif', max_length=1000),
        ),
    ]
