# Generated by Django 2.0 on 2019-08-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingshi_admin', '0007_auto_20190823_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='birthday',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='chathead',
            field=models.CharField(default='upload/default.gif', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='native_place',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='nickname',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='signature',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
