# Generated by Django 2.0 on 2019-08-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingshi_admin', '0008_auto_20190823_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password_hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='isactivation',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='isdel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.IntegerField(choices=[(1, '管理员'), ('2', '普通用户')], default=2),
        ),
    ]
