# Generated by Django 2.0 on 2019-08-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingshi_admin', '0009_auto_20190823_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
