# Generated by Django 2.2 on 2019-08-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lingshi_admin', '0010_user_registration_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods_Category',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='uid',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='User_Info',
        ),
    ]
